/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppSitesRouteImport } from './routes/app.sites'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppEmissionsRouteImport } from './routes/app.emissions'
import { Route as AppDataRouteImport } from './routes/app.data'
import { Route as ApiFactorsRouteImport } from './routes/api.factors'
import { Route as ApiClientsRouteImport } from './routes/api.clients'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminPlatformRouteImport } from './routes/admin.platform'
import { Route as AdminComplianceRouteImport } from './routes/admin.compliance'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSitesRoute = AppSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppEmissionsRoute = AppEmissionsRouteImport.update({
  id: '/emissions',
  path: '/emissions',
  getParentRoute: () => AppRoute,
} as any)
const AppDataRoute = AppDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AppRoute,
} as any)
const ApiFactorsRoute = ApiFactorsRouteImport.update({
  id: '/api/factors',
  path: '/api/factors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientsRoute = ApiClientsRouteImport.update({
  id: '/api/clients',
  path: '/api/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlatformRoute = AdminPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplianceRoute = AdminComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/platform': typeof AdminPlatformRoute
  '/admin/security': typeof AdminSecurityRoute
  '/api/clients': typeof ApiClientsRoute
  '/api/factors': typeof ApiFactorsRoute
  '/app/data': typeof AppDataRoute
  '/app/emissions': typeof AppEmissionsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sites': typeof AppSitesRoute
  '/auth/login': typeof AuthLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/platform': typeof AdminPlatformRoute
  '/admin/security': typeof AdminSecurityRoute
  '/api/clients': typeof ApiClientsRoute
  '/api/factors': typeof ApiFactorsRoute
  '/app/data': typeof AppDataRoute
  '/app/emissions': typeof AppEmissionsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sites': typeof AppSitesRoute
  '/auth/login': typeof AuthLoginRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/platform': typeof AdminPlatformRoute
  '/admin/security': typeof AdminSecurityRoute
  '/api/clients': typeof ApiClientsRoute
  '/api/factors': typeof ApiFactorsRoute
  '/app/data': typeof AppDataRoute
  '/app/emissions': typeof AppEmissionsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sites': typeof AppSitesRoute
  '/auth/login': typeof AuthLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/admin/audit'
    | '/admin/clients'
    | '/admin/compliance'
    | '/admin/platform'
    | '/admin/security'
    | '/api/clients'
    | '/api/factors'
    | '/app/data'
    | '/app/emissions'
    | '/app/history'
    | '/app/reports'
    | '/app/settings'
    | '/app/sites'
    | '/auth/login'
    | '/admin/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/audit'
    | '/admin/clients'
    | '/admin/compliance'
    | '/admin/platform'
    | '/admin/security'
    | '/api/clients'
    | '/api/factors'
    | '/app/data'
    | '/app/emissions'
    | '/app/history'
    | '/app/reports'
    | '/app/settings'
    | '/app/sites'
    | '/auth/login'
    | '/admin'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/admin/audit'
    | '/admin/clients'
    | '/admin/compliance'
    | '/admin/platform'
    | '/admin/security'
    | '/api/clients'
    | '/api/factors'
    | '/app/data'
    | '/app/emissions'
    | '/app/history'
    | '/app/reports'
    | '/app/settings'
    | '/app/sites'
    | '/auth/login'
    | '/admin/'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ApiClientsRoute: typeof ApiClientsRoute
  ApiFactorsRoute: typeof ApiFactorsRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sites': {
      id: '/app/sites'
      path: '/sites'
      fullPath: '/app/sites'
      preLoaderRoute: typeof AppSitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/emissions': {
      id: '/app/emissions'
      path: '/emissions'
      fullPath: '/app/emissions'
      preLoaderRoute: typeof AppEmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/data': {
      id: '/app/data'
      path: '/data'
      fullPath: '/app/data'
      preLoaderRoute: typeof AppDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/factors': {
      id: '/api/factors'
      path: '/api/factors'
      fullPath: '/api/factors'
      preLoaderRoute: typeof ApiFactorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clients': {
      id: '/api/clients'
      path: '/api/clients'
      fullPath: '/api/clients'
      preLoaderRoute: typeof ApiClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/platform': {
      id: '/admin/platform'
      path: '/platform'
      fullPath: '/admin/platform'
      preLoaderRoute: typeof AdminPlatformRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/compliance': {
      id: '/admin/compliance'
      path: '/compliance'
      fullPath: '/admin/compliance'
      preLoaderRoute: typeof AdminComplianceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminComplianceRoute: typeof AdminComplianceRoute
  AdminPlatformRoute: typeof AdminPlatformRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminComplianceRoute: AdminComplianceRoute,
  AdminPlatformRoute: AdminPlatformRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppDataRoute: typeof AppDataRoute
  AppEmissionsRoute: typeof AppEmissionsRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSitesRoute: typeof AppSitesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDataRoute: AppDataRoute,
  AppEmissionsRoute: AppEmissionsRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSitesRoute: AppSitesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ApiClientsRoute: ApiClientsRoute,
  ApiFactorsRoute: ApiFactorsRoute,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
